### ISSUE TITLE
Why are the days not consecutive？

### ISSUE THREAD

**Issue by HTneko** [avalanchesiqi/youtube-engagement#2]
![image](https://user-images.githubusercontent.com/65443985/227519982-66329d3c-308b-437f-a826-f491ddf62a3b.png)
Why are the days not consecutive? Does the missing day represent that all the data for that day are 0?

**Comment by avalanchesiqi** [comment]
Correct. If a day is missing, it means on that day, this video gets zero view (thus zero watch time).

You can recover the date by using the `startDate` field and the `days` field. Each number in the `days` field indicates a time shift (in the unit of day) from the `startDate`.

**Comment by HTneko** [comment]
Thank you for your patient!
